name: Generate Changelog

on:
  push:
    tags:
      - '*'

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.11.0

      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: "highest"

      - name: Generate Changelog
        run: composer changelog

      - name: Create pull-request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Generate Changelog"
          branch: ci-generate-changelog
          base: 'master'
          title: "Generate Changelog"
          delete-branch: true
